project:
  type: website

website:
  title: "Personal webpage"
  site-url: https://archaeothommy.github.io
  repo-url: https://github.com/archaeothommy/archaeothommy.github.io
#  favicon: favicon.png  
navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto
