project:
  type: website
    
website:
  site-url: https://archaeothommy.github.io/
  repo-url: https://github.com/archaeothommy/archaeothommy.github.io/
  favicon: favicon.png
  title: "Personal website"
  navbar:
    left:
#      - text: "Home"
#        href: index.qmd
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto
  