project:
  type: website

website:
  title: "Personal webpage"
  site-url: https://archaeothommy.github.io
  repo-url: https://github.com/archaeothommy/archaeothommy.github.io
#  favicon: favicon.png  
navbar:
    search: true
    left:
      - href: index.qmd
        text: Home
    right: 
      - about.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    